# Site settings
name: name
email: email
url: https://netggio.pe.kr
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: /

# social
github:
  username: alexcha
  
plugins:
  - jekyll-paginate
  

paginate: 5
